"""Theory and estimators for covariance inference after spatial smoothing."""

from HighDimSpatial.smoothing_bias.continuous import (
    ContinuousMultiLagTarget,
    ContinuousFullLikelihoodTarget,
    ContinuousPairTarget,
    FiniteDesignProjectionAsymptotics,
    PairCompositeAsymptotics,
    TransitionPairApproximation,
    continuous_matern_multilag_target,
    continuous_matern_covariance_matrix,
    continuous_matern_full_likelihood_target,
    continuous_matern_pair_target,
    epanechnikov_difference_radial_moment,
    finite_design_full_likelihood_asymptotics,
    gaussian_correlation_kl,
    matern_support_covariance_leading_matrix,
    product_epanechnikov_decay_shift_coefficient,
    product_epanechnikov_direction_contrast_coefficient,
    product_epanechnikov_difference_quadrature,
    product_kernel_decay_shift_coefficient,
    product_kernel_multilag_asymptotics,
    product_uniform_difference_quadrature,
    transition_aware_matern_pair_approximation,
    transformed_epanechnikov_difference_radial_moment,
    uniform_difference_radial_moment,
)
from HighDimSpatial.smoothing_bias.high_dimensional import (
    CandidateLikelihoodBound,
    UniformLikelihoodBound,
    gaussian_likelihood_uniform_bound,
    normalized_gaussian_population_objectives,
    normalized_gaussian_sample_objectives,
    relative_precision_matrix,
)
from HighDimSpatial.smoothing_bias.design import (
    epanechnikov_smoothing_matrix,
    regular_grid_1d,
    regular_grid_2d,
    select_rectangular_centers,
)
from HighDimSpatial.smoothing_bias.estimators import (
    corrected_two_lag_estimate,
    naive_pair_estimate,
)
from HighDimSpatial.smoothing_bias.kl import (
    exact_smoothed_covariance,
    fit_population_log_decay,
    fit_sample_log_decay,
    matern_covariance,
    naive_point_covariance,
)
from HighDimSpatial.smoothing_bias.theory import (
    epanechnikov_far_lag_factor,
    epanechnikov_variance_factor,
    naive_exponential_pseudo_target,
    naive_separable_axis_pseudo_target,
    smoothed_exponential_covariance,
)

__all__ = [
    "ContinuousMultiLagTarget",
    "ContinuousFullLikelihoodTarget",
    "ContinuousPairTarget",
    "FiniteDesignProjectionAsymptotics",
    "PairCompositeAsymptotics",
    "TransitionPairApproximation",
    "corrected_two_lag_estimate",
    "continuous_matern_covariance_matrix",
    "continuous_matern_full_likelihood_target",
    "continuous_matern_multilag_target",
    "continuous_matern_pair_target",
    "epanechnikov_difference_radial_moment",
    "epanechnikov_far_lag_factor",
    "epanechnikov_smoothing_matrix",
    "epanechnikov_variance_factor",
    "exact_smoothed_covariance",
    "fit_population_log_decay",
    "fit_sample_log_decay",
    "finite_design_full_likelihood_asymptotics",
    "gaussian_correlation_kl",
    "matern_support_covariance_leading_matrix",
    "matern_covariance",
    "naive_exponential_pseudo_target",
    "naive_pair_estimate",
    "naive_point_covariance",
    "naive_separable_axis_pseudo_target",
    "product_epanechnikov_decay_shift_coefficient",
    "product_epanechnikov_direction_contrast_coefficient",
    "product_epanechnikov_difference_quadrature",
    "product_kernel_decay_shift_coefficient",
    "product_kernel_multilag_asymptotics",
    "product_uniform_difference_quadrature",
    "transformed_epanechnikov_difference_radial_moment",
    "transition_aware_matern_pair_approximation",
    "uniform_difference_radial_moment",
    "CandidateLikelihoodBound",
    "UniformLikelihoodBound",
    "gaussian_likelihood_uniform_bound",
    "normalized_gaussian_population_objectives",
    "normalized_gaussian_sample_objectives",
    "relative_precision_matrix",
    "regular_grid_1d",
    "regular_grid_2d",
    "select_rectangular_centers",
    "smoothed_exponential_covariance",
]
